sudo: required
language: python

services:
  - docker

before_install:
- docker pull haproxy
script:
- docker run -it --rm --name haproxy-syntax-check -v haproxy.cfg:/tmp/haproxy.cfg haproxy haproxy -c -f /tmp/haproxy.cfg ; echo $?
