sudo: required


services:
  - docker

before_install:
- docker pull haproxy:1.5
- docker run -it --rm --name haproxy-syntax-check haproxy:1.5 haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg
- docker ps -a
script:
- bundle exec rake test
